#!/usr/bin/python3
import subprocess


def main():
    subprocess.run("./install -d", shell=True)
    subprocess.run(".venv/bin/poetry run ansible-playbook ansible/production.yml "
                       "--extra-vars='@ansible/production.conf' --tags "
                       "letsencrypt_auth,"
                       "install_project_production_ini_config,"
                       "install_project_poetry_install_packages,"
                       "install_project_db,"
                       "install_project_permission,"
                       "install_project_nginx_config,"
                       "install_project_uwsgi_config",
                   shell=True)


if __name__ == '__main__':
    main()
