"""add password_status column to users table

Revision ID: 61299f2abd56
Revises: 8af458fe44f9
Create Date: 2019-11-04 11:20:23.528363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61299f2abd56'
down_revision = '8af458fe44f9'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_status', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_status')
    # ### end Alembic commands ###
