"""add order column to group model

Revision ID: 27bbbbe80284
Revises: 6a365a87f821
Create Date: 2020-01-22 21:31:40.207742

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27bbbbe80284'
down_revision = '6a365a87f821'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('order', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'order')
    # ### end Alembic commands ###
