"""add news_categories table

Revision ID: c226a01d0701
Revises: bb7b7040913f
Create Date: 2020-01-16 16:41:14.993467

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c226a01d0701'
down_revision = 'bb7b7040913f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('news', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'news', 'news_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.drop_column('news', 'category_id')
    op.drop_table('news_categories')
    # ### end Alembic commands ###
