"""add sys_settings description column

Revision ID: bb7b7040913f
Revises: 97aa4426362b
Create Date: 2020-01-16 14:26:01.905840

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb7b7040913f'
down_revision = '97aa4426362b'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_settings', sa.Column('description', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sys_settings', 'description')
    # ### end Alembic commands ###
