"""add auth log model

Revision ID: 02cc7bc092be
Revises: a2a44fcb4d23
Create Date: 2021-04-19 11:46:44.773230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02cc7bc092be'
down_revision = 'a2a44fcb4d23'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('client_addr', sa.String(length=48), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_logs')
    # ### end Alembic commands ###
