"""change is_external column name to is_href_blank

Revision ID: 98f94d54a5ca
Revises: 02cc7bc092be
Create Date: 2021-07-27 17:25:52.635630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '98f94d54a5ca'
down_revision = '02cc7bc092be'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('navbar', 'is_external', new_column_name='is_href_blank', existing_type=mysql.INTEGER(),
                                                                              existing_server_default='0',
                                                                              existing_nullable=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('navbar', 'is_href_blank', new_column_name='is_external', existing_type=mysql.INTEGER(),
                                                                              existing_server_default='0',
                                                                              existing_nullable=False)
    # ### end Alembic commands ###
