"""add_depth_column_in_group_model

Revision ID: 7f9bd8a119d1
Revises: bce73c99566a
Create Date: 2024-03-02 22:21:36.667007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f9bd8a119d1'
down_revision = 'bce73c99566a'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('depth', sa.Integer(), server_default='2', nullable=False))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'depth')
    # ### end Alembic commands ###
