"""add is_visible column to news model

Revision ID: 309a6f943d1f
Revises: d1edfc84538f
Create Date: 2025-07-25 17:49:57.657821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '309a6f943d1f'
down_revision = 'd1edfc84538f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('is_visible', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'is_visible')
    # ### end Alembic commands ###
