"""add is_html column in news model

Revision ID: 1ad0bec34604
Revises: 386ef2ab3de8
Create Date: 2025-07-31 15:28:02.833795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ad0bec34604'
down_revision = '386ef2ab3de8'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('is_html', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'is_html')
    # ### end Alembic commands ###
