---
- hosts: localhost
  connection: local
  roles:
    - pylabs.redis
    - pylabs.uwsgi
    - pylabs.letsencrypt_auth
    - pylabs.percona # for ngram support. MariaDB 目前還不支援
  tasks:
    - block:
        - name: import production ini tasks
          import_tasks: _production_ini_tasks.yml
          tags:
            - install_project_production_ini_config
        - name: import theme yascms2020 tasks
          import_tasks: _theme_yascms2020_tasks.yml
          tags:
            - install_project_theme_yascms2020
        - name: 使用 poetry 安裝專案相依套件
          import_tasks: _poetry_install_packages_tasks.yml
          tags:
            - install_project_poetry_install_packages
        - name: import db tasks
          import_tasks: _db_tasks.yml
          tags:
            - install_project_db
        - name: import permission tasks
          import_tasks: _permission_tasks.yml
          tags:
            - install_project_permission
        - name: import nginx tasks
          import_tasks: _nginx_tasks.yml
          tags:
            - install_project_nginx_config
        - name: import uwsgi tasks
          import_tasks: _uwsgi_tasks.yml
          tags:
            - install_project_uwsgi_config
      tags:
        - install_project
  handlers:
    - name: restart redis-server
      ansible.builtin.systemd:
        name: "redis-server.service"
        state: restarted
    - name: reload nginx
      ansible.builtin.systemd:
        name: "nginx.service"
        state: reloaded
